# SPDX-License-Identifier: MIT OR GPL-3.0-or-later
[package]
name = "pacnix-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "pacnix CLI frontend"

[dependencies]
pacnix-core = { path = "../pacnix-core" }
pacnix-backend-alpm = { path = "../pacnix-backend-alpm" }
pacnix-backend-aur = { path = "../pacnix-backend-aur" }
pacnix-backend-nix = { path = "../pacnix-backend-nix" }

[[bin]]
name = "pacnix"
path = "src/main.rs"